// ***********************************************************************
// FILE:        Semaphore.java
// PURPOSE:     Basic semaphore class.
// AUTHOR:      Bruce Jamieson
// MODIFIED:    Andrew Newman
// HISTORY:     30/03/96  Completed.
//              10/08/98  Changed to FIFO Queue for queued processes and
//                        changed to Vector for connected processes. AN
//              11/08/98  Removed iBlocked and iNumConnected. AN
// ***********************************************************************

package Software.IPC;

import java.util.Hashtable;
import java.util.Vector;
import java.lang.String;
import Software.Memory.*;
import Software.Util.FIFOQueue;

public class Semaphore
{
  //Name given by application
  private String sSemaphoreName;
  //Arbitary ID generated by system.
  private int id;
  //ID of process that created the seamphore.
  private int iOwnerPID;
  //Current value in the semaphore.
  private int iValue = -1;
  //List of processes using the semaphore
  private Vector vConnectedProcesses = new Vector();
  //List of process blocked/waiting.
  private FIFOQueue theQueue = new FIFOQueue();

  public Semaphore(String sNewSemaphoreName, int iNewId,
    int iOwnerPID, int iNewValue)
  {
    this.open(iOwnerPID);
    sSemaphoreName = sNewSemaphoreName;
    id = iNewId;
    iValue = iNewValue;
  }

  public int getId()
  {
    return id;
  }

  public String getName()
  {
    return sSemaphoreName;
  }

  public void open(int iPID)
  {
    Integer iNewPID = new Integer(iPID);
    vConnectedProcesses.addElement(iNewPID);
  }

  public int close(int iPID)
  {
    Integer iOldPID = new Integer(iPID);
    vConnectedProcesses.removeElement(iOldPID);
    // IF there are no connections open to the sem, then the
    // sem should die...
    // Do this by returning the number connected
    // (Let someone else deal with the problem...)
    return (vConnectedProcesses.size());
  }

  public int signal()
  {
    // Raise the value of the semaphore OR return the
    // 1st id in the blocked Q...
    if (theQueue.size() == 0)
    {
      iValue++;
      // No one blocked so return -1
      return -1;
    }
    else
    {
      // Get the first element and remove it
      Integer iOldPID = (Integer) theQueue.retrieve();
      return (iOldPID.intValue());
    }
  }

  public int wait(int iPID)
  {
    // Dec the value of the semaphore OR add to the blocked Q
    if (iValue == 0)
    {
      //Add to the blocked Q and signal as such
      Integer iNewPID = new Integer(iPID);
      theQueue.insert(iNewPID);
      return -1;
    }
    else
    {
      iValue--;
      return iValue;
    }
  }
}
